import type { Predeploy } from '../types';

// L1 contracts configuration
// Note: Using Predeploy type for compatibility with existing components
// Addresses are read from environment variables to support different OP Stack chains
export const L1_CONTRACTS: Predeploy[] = [
  {
    name: 'AnchorStateRegistry',
    address: process.env.REACT_APP_L1_ANCHOR_STATE_REGISTRY_ADDRESS || '',
    description: 'Anchor state registry for L2 state commitments',
    category: 'system',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'disputeGameFinalityDelaySeconds', label: 'Dispute Game Finality Delay (seconds)' },
      { name: 'systemConfig', label: 'System Config' },
      { name: 'disputeGameFactory', label: 'Dispute Game Factory' },
      { name: 'anchorGame', label: 'Anchor Game' },
      { name: 'respectedGameType', label: 'Respected Game Type' },
      { name: 'retirementTimestamp', label: 'Retirement Timestamp' },
      { name: 'paused', label: 'Paused' },
      { name: 'getAnchorRoot', label: 'Anchor Root' },
    ],
  },
  {
    name: 'DisputeGameFactory',
    address: process.env.REACT_APP_L1_DISPUTE_GAME_FACTORY_ADDRESS || '',
    description: 'Factory for creating dispute games',
    category: 'system',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'portalAddress', label: 'Portal Address' },
      { name: 'proverRegistryAddress', label: 'Prover Registry Address' },
      { name: 'getBlockNumber', label: 'Block Number' },
      { name: 'getCurrentOffset', label: 'Current Offset' },
      { name: 'gameCount', label: 'Game Count' },
      // Mapping results (dynamically added if non-zero)
      { name: 'gameImpls_Permissionless', label: 'Game Impl (Permissionless)' },
      { name: 'gameImpls_Permissioned', label: 'Game Impl (Permissioned)' },
      { name: 'gameImpls_OP_SUCCINCT', label: 'Game Impl (OP_SUCCINCT)' },
      { name: 'initBonds_Permissionless', label: 'Init Bond (Permissionless)' },
      { name: 'initBonds_Permissioned', label: 'Init Bond (Permissioned)' },
      { name: 'initBonds_OP_SUCCINCT', label: 'Init Bond (OP_SUCCINCT)' },
    ],
  },
  {
    name: 'L1StandardBridge',
    address: process.env.REACT_APP_L1_STANDARD_BRIDGE_ADDRESS || '',
    description: 'L1 standard bridge for cross-chain transfers',
    category: 'bridge',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'signalService', label: 'Signal Service' },
      { name: 'systemConfig', label: 'System Config' },
      { name: 'paused', label: 'Paused' },
    ],
  },
  {
    name: 'OptimismPortal',
    address: process.env.REACT_APP_L1_OPTIMISM_PORTAL_ADDRESS || '',
    description: 'Portal for L1 <> L2 communication',
    category: 'bridge',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'proofMaturityDelaySeconds', label: 'Proof Maturity Delay (seconds)' },
      { name: 'systemConfig', label: 'System Config' },
      { name: 'anchorStateRegistry', label: 'Anchor State Registry' },
      { name: 'paused', label: 'Paused' },
      { name: 'disputeGameFactory', label: 'Dispute Game Factory' },
    ],
  },
  {
    name: 'ProxyAdmin',
    address: process.env.REACT_APP_L1_PROXY_ADMIN_ADDRESS || '',
    description: 'Owner of L1 contract proxies',
    category: 'system',
    isManageable: true,
    isOwnerBased: true, // Has owner() but is not a proxy contract
  },
  {
    name: 'SystemConfig',
    address: process.env.REACT_APP_L1_SYSTEM_CONFIG_ADDRESS || '',
    description: 'System configuration contract',
    category: 'system',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'guardian', label: 'Guardian' },
      { name: 'superchainConfig', label: 'Superchain Config' },
      { name: 'batcherHash', label: 'Batcher Hash' },
      { name: 'gasLimit', label: 'Gas Limit' },
      { name: 'basefeeScalar', label: 'Base Fee Scalar' },
      { name: 'blobbasefeeScalar', label: 'Blob Base Fee Scalar' },
      { name: 'eip1559Denominator', label: 'EIP-1559 Denominator' },
      { name: 'eip1559Elasticity', label: 'EIP-1559 Elasticity' },
      { name: 'operatorFeeScalar', label: 'Operator Fee Scalar' },
      { name: 'operatorFeeConstant', label: 'Operator Fee Constant' },
      { name: 'l2ChainId', label: 'L2 Chain ID' },
      { name: 'unsafeBlockSigner', label: 'Unsafe Block Signer' },
      { name: 'l1CrossDomainMessenger', label: 'L1 Cross Domain Messenger' },
      { name: 'l1StandardBridge', label: 'L1 Standard Bridge' },
      { name: 'disputeGameFactory', label: 'Dispute Game Factory' },
      { name: 'optimismPortal', label: 'Optimism Portal' },
      { name: 'batchInbox', label: 'Batch Inbox' },
      { name: 'startBlock', label: 'Start Block' },
      { name: 'paused', label: 'Paused' },
      // Resource Config components (expanded from tuple)
      { name: 'resourceConfig_maxResourceLimit', label: 'Resource Config - Max Resource Limit' },
      { name: 'resourceConfig_elasticityMultiplier', label: 'Resource Config - Elasticity Multiplier' },
      { name: 'resourceConfig_baseFeeMaxChangeDenominator', label: 'Resource Config - Base Fee Max Change Denominator' },
      { name: 'resourceConfig_minimumBaseFee', label: 'Resource Config - Minimum Base Fee' },
      { name: 'resourceConfig_systemTxMaxGas', label: 'Resource Config - System Tx Max Gas' },
      { name: 'resourceConfig_maximumBaseFee', label: 'Resource Config - Maximum Base Fee' },
    ],
  },
  {
    name: 'SuperchainConfig',
    address: process.env.REACT_APP_L1_SUPERCHAIN_CONFIG_ADDRESS || '',
    description: 'Superchain configuration and pause management',
    category: 'system',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'guardian', label: 'Guardian' },
      { name: 'pauseExpiry', label: 'Pause Expiry (seconds)' },
      { name: 'paused_global', label: 'ALL PAUSED' },
      { name: 'paused_portal', label: 'PORTAL PAUSED' },
      { name: 'expiration_global', label: 'All Pause Expiration' },
      { name: 'expiration_portal', label: 'Portal Pause Expiration' },
    ],
  },
  {
    name: 'SignalService',
    address: process.env.REACT_APP_L1_SIGNAL_SERVICE_ADDRESS || '',
    description: 'L1 Signal service for cross-chain communication',
    category: 'system',
    isManageable: false,
    viewFunctions: [], // Not a proxy contract - no admin/implementation to display
  },
  {
    name: 'ProverRegistry',
    address: process.env.REACT_APP_L1_PROVER_REGISTRY_ADDRESS || '',
    description: 'Registry for TEE provers and attestation verification',
    category: 'tee',
    isManageable: true,
    isOwnerBased: true, // Has owner() but is not a proxy contract
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'chainID', label: 'Chain ID' },
      { name: 'verifier', label: 'Verifier' },
      { name: 'requiredProverTypes', label: 'Required Prover Types' },
      { name: 'attestValiditySeconds', label: 'Attest Validity (seconds)' },
      { name: 'maxBlockNumberDiff', label: 'Max Block Number Diff' },
      { name: 'nextInstanceId', label: 'Next Instance ID' },
    ],
  },
  {
    name: 'WorkloadVerifier',
    address: process.env.REACT_APP_L1_WORKLOAD_VERIFIER_ADDRESS || '',
    description: 'Workload verifier for TEE attestations',
    category: 'tee',
    isManageable: true,
    isOwnerBased: true, // Has owner() but is not a proxy contract
    viewFunctions: [
      { name: 'dcapAttestation', label: 'DCAP Attestation' },
      { name: 'snpAttestation', label: 'SNP Attestation' },
      { name: 'tpmAttestation', label: 'TPM Attestation' },
    ],
  },
];
