import type { Predeploy } from '../types';

// L1 contracts configuration
// Note: Using Predeploy type for compatibility with existing components
export const L1_CONTRACTS: Predeploy[] = [
  // Placeholder contracts - will be populated with actual details
  {
    name: 'AnchorStateRegistry',
    address: '0x5415b132cb934066dc9bf1924a0cad9fb4eed07e',
    description: 'Anchor state registry for L2 state commitments',
    category: 'system',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'disputeGameFinalityDelaySeconds', label: 'Dispute Game Finality Delay (seconds)' },
      { name: 'systemConfig', label: 'System Config' },
      { name: 'disputeGameFactory', label: 'Dispute Game Factory' },
      { name: 'anchorGame', label: 'Anchor Game' },
      { name: 'respectedGameType', label: 'Respected Game Type' },
      { name: 'retirementTimestamp', label: 'Retirement Timestamp' },
      { name: 'paused', label: 'Paused' },
      { name: 'getAnchorRoot', label: 'Anchor Root' },
    ],
  },
  {
    name: 'DisputeGameFactory',
    address: '0xC3566eB389bA4e6c378f6f0a7e99C32033AeA9D4',
    description: 'Factory for creating dispute games',
    category: 'system',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'portalAddress', label: 'Portal Address' },
      { name: 'proverRegistryAddress', label: 'Prover Registry Address' },
      { name: 'getBlockNumber', label: 'Block Number' },
      { name: 'getCurrentOffset', label: 'Current Offset' },
      { name: 'gameCount', label: 'Game Count' },
      // Mapping results (dynamically added if non-zero)
      { name: 'gameImpls_Permissionless', label: 'Game Impl (Permissionless)' },
      { name: 'gameImpls_Permissioned', label: 'Game Impl (Permissioned)' },
      { name: 'gameImpls_OP_SUCCINCT', label: 'Game Impl (OP_SUCCINCT)' },
      { name: 'initBonds_Permissionless', label: 'Init Bond (Permissionless)' },
      { name: 'initBonds_Permissioned', label: 'Init Bond (Permissioned)' },
      { name: 'initBonds_OP_SUCCINCT', label: 'Init Bond (OP_SUCCINCT)' },
    ],
  },
  {
    name: 'EthLockbox',
    address: '0x0000000000000000000000000000000000000000', // TODO: Add actual address when deployed
    description: 'ETH lockbox for bridging',
    category: 'bridge',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'systemConfig', label: 'System Config' },
      { name: 'paused', label: 'Paused' },
    ],
  },
  {
    name: 'L1StandardBridge',
    address: '0xa99A27d6F39630332e0F39C9Fa3D2E0C0d76B3e7',
    description: 'L1 standard bridge for cross-chain transfers',
    category: 'bridge',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'signalService', label: 'Signal Service' },
      { name: 'systemConfig', label: 'System Config' },
      { name: 'paused', label: 'Paused' },
    ],
  },
  {
    name: 'OptimismPortal',
    address: '0x0E9c3F12dcA3494D7A6d96bF47FB1d45E949A4B2',
    description: 'Portal for L1 <> L2 communication',
    category: 'bridge',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'proofMaturityDelaySeconds', label: 'Proof Maturity Delay (seconds)' },
      { name: 'systemConfig', label: 'System Config' },
      { name: 'ethLockbox', label: 'ETH Lockbox' },
      { name: 'anchorStateRegistry', label: 'Anchor State Registry' },
      { name: 'paused', label: 'Paused' },
      { name: 'disputeGameFactory', label: 'Dispute Game Factory' },
    ],
  },
  {
    name: 'ProxyAdmin',
    address: '0xd3D6C903D4B4a2199439F4147CC4Ac4781bC5016',
    description: 'Owner of L1 contract proxies',
    category: 'system',
    isManageable: true,
  },
  {
    name: 'SystemConfig',
    address: '0x3c2b21BAD19002D888B25a183BcDae97ab520B7c',
    description: 'System configuration contract',
    category: 'system',
    isManageable: true,
    viewFunctions: [
      { name: 'version', label: 'Version' },
      { name: 'batcherHash', label: 'Batcher Hash' },
      { name: 'gasLimit', label: 'Gas Limit' },
      { name: 'basefeeScalar', label: 'Base Fee Scalar' },
      { name: 'blobbasefeeScalar', label: 'Blob Base Fee Scalar' },
      { name: 'eip1559Denominator', label: 'EIP-1559 Denominator' },
      { name: 'eip1559Elasticity', label: 'EIP-1559 Elasticity' },
      { name: 'operatorFeeScalar', label: 'Operator Fee Scalar' },
      { name: 'operatorFeeConstant', label: 'Operator Fee Constant' },
      { name: 'l2ChainId', label: 'L2 Chain ID' },
      { name: 'unsafeBlockSigner', label: 'Unsafe Block Signer' },
      { name: 'l1CrossDomainMessenger', label: 'L1 Cross Domain Messenger' },
      { name: 'l1StandardBridge', label: 'L1 Standard Bridge' },
      { name: 'disputeGameFactory', label: 'Dispute Game Factory' },
      { name: 'optimismPortal', label: 'Optimism Portal' },
      { name: 'batchInbox', label: 'Batch Inbox' },
      { name: 'startBlock', label: 'Start Block' },
      { name: 'paused', label: 'Paused' },
      // Resource Config components (expanded from tuple)
      { name: 'resourceConfig_maxResourceLimit', label: 'Resource Config - Max Resource Limit' },
      { name: 'resourceConfig_elasticityMultiplier', label: 'Resource Config - Elasticity Multiplier' },
      { name: 'resourceConfig_baseFeeMaxChangeDenominator', label: 'Resource Config - Base Fee Max Change Denominator' },
      { name: 'resourceConfig_minimumBaseFee', label: 'Resource Config - Minimum Base Fee' },
      { name: 'resourceConfig_systemTxMaxGas', label: 'Resource Config - System Tx Max Gas' },
      { name: 'resourceConfig_maximumBaseFee', label: 'Resource Config - Maximum Base Fee' },
    ],
  },
];
